### PR TITLE
prepare release 2.0.0

### PR DESCRIPTION
**Pull request by mandar242**
##### SUMMARY
- Run `antsibull-changelog` to generate release notes.
- Update `galaxy.yml` version to `2.0.0`

##### ISSUE TYPE
- Release Pull Request

### CODE REVIEW

**Comment by mandar242** [comment]
recheck

**Review by hakbailey — APPROVED** [review]

**Comment by alinabuzachis** [comment]
Can you please rename the stable-2.0 branch to stable-2 to follow the naming of the other collections?

**Comment by alinabuzachis** [comment]
Please also note that you need to update documentation links to use stable-2 rather than main before prepping the release PR.

**Comment by GomathiselviS** [comment]
[This PR](https://github.com/redhat-cop/cloud.gcp_ops/pull/16) has to be merged, before the release PR is prepared.

**Comment by mandar242** [comment]
> Please also note that you need to update documentation links to use stable-2 rather than main before prepping the release PR.

no worries, let me know once everything is merged, I'll redo this one

**Comment by mandar242** [comment]
closed as rework required after #16 gets merged

**Pull request closed without merging**
